package com.sunmo.stockplatform.scanner.domain;
import jakarta.persistence.*;
import java.math.BigDecimal;import java.time.Instant;
@Entity @Table(name="scanner_setting")
public class ScannerSetting {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id;@Column(name="owner_id",nullable=false)private Long ownerId;@Column(nullable=false,length=100)private String name;@Enumerated(EnumType.STRING)@Column(name="scanner_type",nullable=false)private ScannerType type;
 @Column(name="min_change_rate",nullable=false,precision=12,scale=6)private BigDecimal minChangeRate;@Column(name="min_volume_ratio",nullable=false,precision=12,scale=6)private BigDecimal minVolumeRatio;@Column(name="min_5m_trading_value",nullable=false,precision=20,scale=4)private BigDecimal minFiveMinuteTradingValue;@Column(name="min_daily_trading_value",nullable=false,precision=20,scale=4)private BigDecimal minDailyTradingValue;@Column(name="min_price",nullable=false,precision=20,scale=4)private BigDecimal minPrice;@Column(name="include_etf",nullable=false)private boolean includeEtf;@Column(name="cooldown_seconds",nullable=false)private int cooldownSeconds;@Column(name="is_active",nullable=false)private boolean active;@Version private long version;@Column(name="created_at",nullable=false,updatable=false)private Instant createdAt;@Column(name="updated_at",nullable=false)private Instant updatedAt;
 protected ScannerSetting(){} public ScannerSetting(Long owner,String name,ScannerType type,BigDecimal change,BigDecimal ratio,BigDecimal fiveValue,BigDecimal dailyValue,BigDecimal minPrice,boolean includeEtf,int cooldown){this.ownerId=owner;this.name=name;this.type=type;update(name,change,ratio,fiveValue,dailyValue,minPrice,includeEtf,cooldown,true);}
 public void update(String name,BigDecimal change,BigDecimal ratio,BigDecimal fiveValue,BigDecimal dailyValue,BigDecimal minPrice,boolean includeEtf,int cooldown,boolean active){this.name=name;this.minChangeRate=change;this.minVolumeRatio=ratio;this.minFiveMinuteTradingValue=fiveValue;this.minDailyTradingValue=dailyValue;this.minPrice=minPrice;this.includeEtf=includeEtf;this.cooldownSeconds=cooldown;this.active=active;}
 @PrePersist void create(){createdAt=Instant.now();updatedAt=createdAt;}@PreUpdate void touch(){updatedAt=Instant.now();}
 public Long getId(){return id;}public String getName(){return name;}public ScannerType getType(){return type;}public BigDecimal getMinChangeRate(){return minChangeRate;}public BigDecimal getMinVolumeRatio(){return minVolumeRatio;}public BigDecimal getMinFiveMinuteTradingValue(){return minFiveMinuteTradingValue;}public BigDecimal getMinDailyTradingValue(){return minDailyTradingValue;}public BigDecimal getMinPrice(){return minPrice;}public boolean isIncludeEtf(){return includeEtf;}public int getCooldownSeconds(){return cooldownSeconds;}public boolean isActive(){return active;}public long getVersion(){return version;}
}
