package com.sunmo.stockplatform.scanner;
import com.sunmo.stockplatform.candle.application.CandleSnapshot;import com.sunmo.stockplatform.candle.domain.StockCandle;import com.sunmo.stockplatform.scanner.application.ScannerEvaluator;import org.junit.jupiter.api.Test;import java.math.BigDecimal;import java.time.Instant;import java.util.*;import static org.assertj.core.api.Assertions.*;
class ScannerEvaluatorTest {
 private final ScannerEvaluator evaluator=new ScannerEvaluator();
 @Test void calculatesGoldenMomentumMetrics(){List<StockCandle> previous=new ArrayList<>();for(int i=0;i<6;i++)previous.add(candle(Instant.parse("2026-08-18T00:25:00Z").minusSeconds(i*300L),"100",10));CandleSnapshot current=new CandleSnapshot("005930",Instant.parse("2026-08-18T00:30:00Z"),bd("100"),bd("105"),bd("99"),bd("105"),30,bd("3150"),false,0);var metrics=evaluator.calculate(current,previous);assertThat(metrics.ready()).isTrue();assertThat(metrics.volumeRatio()).isEqualByComparingTo("3.000000");assertThat(metrics.changeRate()).isEqualByComparingTo("5.000000");assertThat(metrics.score()).isEqualByComparingTo("8.000000");}
 @Test void requiresSixHistoricalBuckets(){var metrics=evaluator.calculate(new CandleSnapshot("005930",Instant.now(),bd("100"),bd("100"),bd("100"),bd("100"),1,bd("100"),false,0),List.of(candle(Instant.now(),"100",1)));assertThat(metrics.ready()).isFalse();assertThat(metrics.reason()).isEqualTo("INSUFFICIENT_HISTORY");}
 @Test void excludesZeroBaselineVolume(){List<StockCandle> previous=new ArrayList<>();for(int i=0;i<6;i++)previous.add(candle(Instant.now().minusSeconds(i*300L),"100",0));var metrics=evaluator.calculate(new CandleSnapshot("005930",Instant.now(),bd("100"),bd("100"),bd("100"),bd("100"),10,bd("1000"),false,0),previous);assertThat(metrics.reason()).isEqualTo("UNDEFINED_BASELINE");}
 private StockCandle candle(Instant at,String close,long volume){return new StockCandle(null,at,bd(close),bd(close),bd(close),bd(close),volume,bd("0"),true,0);}private BigDecimal bd(String v){return new BigDecimal(v);}
}
