package com.sunmo.stockplatform.scanner;
import com.sunmo.stockplatform.candle.application.CandleSnapshot;import com.sunmo.stockplatform.candle.domain.StockCandle;import com.sunmo.stockplatform.market.feature.domain.MarketFeatureSnapshot;import com.sunmo.stockplatform.scanner.application.ScannerEvaluator;import com.sunmo.stockplatform.scanner.domain.*;import org.junit.jupiter.api.Test;import java.math.BigDecimal;import java.time.*;import java.util.*;import static org.assertj.core.api.Assertions.*;
class ScannerEvaluatorTest {
 private final ScannerEvaluator evaluator=new ScannerEvaluator();
 @Test void calculatesGoldenMomentumMetrics(){List<StockCandle> previous=new ArrayList<>();for(int i=0;i<6;i++)previous.add(candle(Instant.parse("2026-08-18T00:25:00Z").minusSeconds(i*300L),"100",10));CandleSnapshot current=new CandleSnapshot("005930",Instant.parse("2026-08-18T00:30:00Z"),bd("100"),bd("105"),bd("99"),bd("105"),30,bd("3150"),false,0);var metrics=evaluator.calculate(current,previous);assertThat(metrics.ready()).isTrue();assertThat(metrics.volumeRatio()).isEqualByComparingTo("3.000000");assertThat(metrics.changeRate()).isEqualByComparingTo("5.000000");assertThat(metrics.score()).isEqualByComparingTo("8.000000");}
 @Test void requiresSixHistoricalBuckets(){var metrics=evaluator.calculate(new CandleSnapshot("005930",Instant.now(),bd("100"),bd("100"),bd("100"),bd("100"),1,bd("100"),false,0),List.of(candle(Instant.now(),"100",1)));assertThat(metrics.ready()).isFalse();assertThat(metrics.reason()).isEqualTo("INSUFFICIENT_HISTORY");}
 @Test void excludesZeroBaselineVolume(){List<StockCandle> previous=new ArrayList<>();for(int i=0;i<6;i++)previous.add(candle(Instant.now().minusSeconds(i*300L),"100",0));var metrics=evaluator.calculate(new CandleSnapshot("005930",Instant.now(),bd("100"),bd("100"),bd("100"),bd("100"),10,bd("1000"),false,0),previous);assertThat(metrics.reason()).isEqualTo("UNDEFINED_BASELINE");}
 @Test void detectsAdvancedScannerTypesFromMetricsAndFeatures(){List<StockCandle> previous=new ArrayList<>();for(int i=0;i<6;i++)previous.add(candle(Instant.parse("2026-08-18T00:25:00Z").minusSeconds(i*300L),"100",10));CandleSnapshot current=new CandleSnapshot("005930",Instant.parse("2026-08-18T00:30:00Z"),bd("100"),bd("106"),bd("99"),bd("105"),30,bd("3150"),false,0);var metrics=evaluator.calculate(current,previous);assertThat(evaluator.evaluate(setting(ScannerType.VOLUME_BREAKOUT,z(),bd("2")),metrics,current,bd("10000"),feature()).matched()).isTrue();assertThat(evaluator.evaluate(setting(ScannerType.TURNOVER_BREAKOUT,z(),bd("2")),metrics,current,bd("10000"),feature()).matched()).isTrue();assertThat(evaluator.evaluate(setting(ScannerType.HIGH_BREAKOUT,bd("1"),z()),metrics,current,bd("10000"),feature()).matched()).isTrue();assertThat(evaluator.evaluate(setting(ScannerType.VWAP_BREAKOUT,bd("1"),z()),metrics,current,bd("10000"),feature()).matched()).isTrue();assertThat(evaluator.evaluate(setting(ScannerType.VWAP_RECLAIM,bd("1"),z()),metrics,current,bd("10000"),feature()).matched()).isTrue();}
 @Test void returnsStructuredReasonWhenMatched(){List<StockCandle> previous=new ArrayList<>();for(int i=0;i<6;i++)previous.add(candle(Instant.parse("2026-08-18T00:25:00Z").minusSeconds(i*300L),"100",10));CandleSnapshot current=new CandleSnapshot("005930",Instant.parse("2026-08-18T00:30:00Z"),bd("100"),bd("106"),bd("99"),bd("105"),30,bd("3150"),false,0);var decision=evaluator.evaluate(setting(ScannerType.VWAP_BREAKOUT,bd("1"),z()),evaluator.calculate(current,previous),current,bd("10000"),feature());assertThat(decision.reasonJson()).contains("\"version\":\"scanner-reason-v1\"");assertThat(decision.reasonJson()).contains("\"type\":\"VWAP_BREAKOUT\"");assertThat(decision.reasonJson()).contains("\"state\":\"MATCHED\"");}
 private StockCandle candle(Instant at,String close,long volume){return new StockCandle(null,at,bd(close),bd(close),bd(close),bd(close),volume,bd("0"),true,0);}private BigDecimal bd(String v){return new BigDecimal(v);}
 private BigDecimal z(){return BigDecimal.ZERO;}
 private ScannerSetting setting(ScannerType type,BigDecimal change,BigDecimal ratio){return new ScannerSetting(1L,type.name(),type,change,ratio,z(),z(),z(),false,300);}
 private MarketFeatureSnapshot feature(){return new MarketFeatureSnapshot("005930",LocalDate.parse("2026-08-18"),Instant.parse("2026-08-18T00:30:01Z"),bd("105"),100,bd("10000"),bd("100"),bd("106"),bd("99"),bd("102"),bd("2.941176"),bd("0.100000"),bd("3.0"),bd("2.5"),bd("130"),20,5,bd("60"),bd("0.2"),false,z(),MarketFeatureSnapshot.VERSION);}
}
