package com.sunmo.stockplatform.scanner.application;
import com.sunmo.stockplatform.candle.application.CandleSnapshot;import com.sunmo.stockplatform.analytics.application.DetectionPerformanceTracker;import com.sunmo.stockplatform.candle.infrastructure.StockCandleRepository;import com.sunmo.stockplatform.market.application.*;import com.sunmo.stockplatform.scanner.domain.*;import com.sunmo.stockplatform.scanner.infrastructure.*;import com.sunmo.stockplatform.stock.domain.Stock;import com.sunmo.stockplatform.stock.infrastructure.StockRepository;import org.springframework.beans.factory.ObjectProvider;import org.springframework.data.redis.core.StringRedisTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;import java.time.Duration;import java.util.*;import java.util.concurrent.ConcurrentHashMap;
@Service
public class ScannerEngine {
 private static final long OWNER=1L;private final ScannerSettingRepository settings;private final ScannerDetectionRepository detections;private final StockRepository stocks;private final StockCandleRepository candles;private final QuoteStateStore quotes;private final ScannerEvaluator evaluator;private final MarketEventGateway events;private final StringRedisTemplate redis;private final DetectionPerformanceTracker tracker;private final RealtimeDiagnostics diagnostics;private final Map<String,Integer> misses=new ConcurrentHashMap<>();private final Set<String> inside=ConcurrentHashMap.newKeySet();
 public ScannerEngine(ScannerSettingRepository settings,ScannerDetectionRepository detections,StockRepository stocks,StockCandleRepository candles,QuoteStateStore quotes,ScannerEvaluator evaluator,MarketEventGateway events,ObjectProvider<StringRedisTemplate> redis,DetectionPerformanceTracker tracker,RealtimeDiagnostics diagnostics){this.settings=settings;this.detections=detections;this.stocks=stocks;this.candles=candles;this.quotes=quotes;this.evaluator=evaluator;this.events=events;this.redis=redis.getIfAvailable();this.tracker=tracker;this.diagnostics=diagnostics;}
 @Transactional public void evaluate(CandleSnapshot current){diagnostics.scannerEvaluated();Stock stock=stocks.findByStockCodeAndActiveTrue(current.stockCode()).orElse(null);if(stock==null||stock.isManaged()||stock.isTradingHalted())return;var previous=candles.findTop6ByStockIdAndTimeframeAndStartTimeBeforeOrderByStartTimeDesc(stock.getId(),"5M",current.startTime());var metrics=evaluator.calculate(current,previous);BigDecimal daily=quotes.get(current.stockCode()).map(t->t.cumulativeTradingValue()).orElse(null);for(ScannerSetting setting:settings.findByOwnerIdAndActiveTrue(OWNER)){String state=setting.getId()+":"+current.stockCode();boolean match=(!stock.isEtf()&&!stock.isEtn()||setting.isIncludeEtf())&&evaluator.matches(setting,metrics,current,daily);if(!match){if(inside.contains(state)&&misses.merge(state,1,Integer::sum)>=2){inside.remove(state);misses.remove(state);}continue;}misses.remove(state);if(!inside.add(state))continue;UUID eventId=UUID.randomUUID();if(!acquire(setting,current.stockCode(),eventId)){inside.remove(state);continue;}String snapshot=snapshot(setting);java.time.Instant detectedAt=java.time.Instant.now();ScannerDetection detection=detections.save(new ScannerDetection(eventId,stock,setting,detectedAt,current.close(),metrics.changeRate(),metrics.volumeRatio(),current.volume(),current.tradingValue(),daily,metrics.score(),snapshot,"candle:"+current.startTime()));tracker.initialize(detection);diagnostics.detectionCreated();rank(setting,stock,metrics.score());events.publish("scanner."+eventName(setting.getType())+".detected",Map.of("detectionId",detection.getId(),"eventId",eventId.toString(),"stockCode",stock.getStockCode(),"stockName",stock.getStockName(),"price",current.close().toPlainString(),"changeRate",metrics.changeRate().toPlainString(),"volumeRatio",metrics.volumeRatio().toPlainString(),"score",metrics.score().toPlainString()));}}
 private void rank(ScannerSetting setting,Stock stock,BigDecimal score){try{String key="scanner:"+setting.getType()+":rank:"+setting.getId();redis.opsForZSet().add(key,stock.getStockCode(),score.doubleValue());redis.expire(key,Duration.ofMinutes(10));}catch(RuntimeException ignored){}}
 private boolean acquire(ScannerSetting setting,String code,UUID event){if(redis==null)return false;try{Boolean ok=redis.opsForValue().setIfAbsent("scanner:"+setting.getType()+":cooldown:"+setting.getId()+":"+code,event.toString(),Duration.ofSeconds(setting.getCooldownSeconds()));return Boolean.TRUE.equals(ok);}catch(RuntimeException error){return false;}}
 private String eventName(ScannerType type){return switch(type){case VOLUME->"volume";case PRICE_RISE->"price";case MOMENTUM->"momentum";};}
 private String snapshot(ScannerSetting s){return "{\"algorithmVersion\":\"momentum-v1\",\"type\":\""+s.getType()+"\",\"minChangeRate\":\""+s.getMinChangeRate()+"\",\"minVolumeRatio\":\""+s.getMinVolumeRatio()+"\",\"min5mTradingValue\":\""+s.getMinFiveMinuteTradingValue()+"\",\"minDailyTradingValue\":\""+s.getMinDailyTradingValue()+"\",\"cooldownSeconds\":"+s.getCooldownSeconds()+"}";}
}
