package com.sunmo.stockplatform.analytics.domain;
import com.sunmo.stockplatform.scanner.domain.ScannerDetection;import jakarta.persistence.*;import java.math.*;import java.time.*;
@Entity @Table(name="detection_performance")
public class DetectionPerformance {
 @Id @Column(name="detection_id")private Long detectionId;@MapsId @OneToOne(fetch=FetchType.LAZY,optional=false)@JoinColumn(name="detection_id")private ScannerDetection detection;
 @Column(name="price_5m",precision=20,scale=4)private BigDecimal price5m;@Column(name="price_10m",precision=20,scale=4)private BigDecimal price10m;@Column(name="price_30m",precision=20,scale=4)private BigDecimal price30m;@Column(name="price_60m",precision=20,scale=4)private BigDecimal price60m;@Column(name="close_price",precision=20,scale=4)private BigDecimal closePrice;@Column(name="highest_price",precision=20,scale=4)private BigDecimal highestPrice;@Column(name="lowest_price",precision=20,scale=4)private BigDecimal lowestPrice;
 @Column(name="return_5m",precision=12,scale=6)private BigDecimal return5m;@Column(name="return_10m",precision=12,scale=6)private BigDecimal return10m;@Column(name="return_30m",precision=12,scale=6)private BigDecimal return30m;@Column(name="return_60m",precision=12,scale=6)private BigDecimal return60m;@Column(name="return_close",precision=12,scale=6)private BigDecimal returnClose;@Column(name="max_return",precision=12,scale=6)private BigDecimal maxReturn;@Column(name="max_drawdown",precision=12,scale=6)private BigDecimal maxDrawdown;
 @Enumerated(EnumType.STRING)@Column(nullable=false)private PerformanceStatus status;@Column(name="calculation_version",nullable=false)private String calculationVersion;@Column(name="observed_5m_at")private Instant observed5mAt;@Column(name="observed_10m_at")private Instant observed10mAt;@Column(name="observed_30m_at")private Instant observed30mAt;@Column(name="observed_60m_at")private Instant observed60mAt;@Column(name="close_observed_at")private Instant closeObservedAt;@Column(name="finalized_at")private Instant finalizedAt;@Column(name="updated_at",nullable=false)private Instant updatedAt;@Version private long version;
 protected DetectionPerformance(){}public DetectionPerformance(ScannerDetection detection){this.detection=detection;this.status=PerformanceStatus.PENDING;this.calculationVersion="performance-v1";this.highestPrice=detection.getDetectedPrice();this.lowestPrice=detection.getDetectedPrice();this.updatedAt=Instant.now();}
 public void observe(BigDecimal price,Instant at){if(status!=PerformanceStatus.PENDING)return;highestPrice=highestPrice.max(price);lowestPrice=lowestPrice.min(price);long seconds=Duration.between(detection.getDetectedAt(),at).getSeconds();if(seconds>=300&&price5m==null){price5m=price;observed5mAt=at;}if(seconds>=600&&price10m==null){price10m=price;observed10mAt=at;}if(seconds>=1800&&price30m==null){price30m=price;observed30mAt=at;}if(seconds>=3600&&price60m==null){price60m=price;observed60mAt=at;}recalculate();updatedAt=Instant.now();}
 public void finalizeClose(BigDecimal price,Instant at){if(price!=null){highestPrice=highestPrice.max(price);lowestPrice=lowestPrice.min(price);closePrice=price;closeObservedAt=at;}recalculate();status=allMilestones()?PerformanceStatus.COMPLETED:PerformanceStatus.DATA_MISSING;finalizedAt=at;updatedAt=at;}
 private boolean allMilestones(){return price5m!=null&&price10m!=null&&price30m!=null&&price60m!=null&&closePrice!=null;}private void recalculate(){BigDecimal base=detection.getDetectedPrice();return5m=pct(price5m,base);return10m=pct(price10m,base);return30m=pct(price30m,base);return60m=pct(price60m,base);returnClose=pct(closePrice,base);maxReturn=pct(highestPrice,base);maxDrawdown=pct(lowestPrice,base);}private BigDecimal pct(BigDecimal value,BigDecimal base){return value==null?null:value.subtract(base).divide(base,8,RoundingMode.HALF_UP).multiply(BigDecimal.valueOf(100)).setScale(6,RoundingMode.HALF_UP);}
 public Long getDetectionId(){return detectionId;}public ScannerDetection getDetection(){return detection;}public BigDecimal getPrice5m(){return price5m;}public BigDecimal getPrice10m(){return price10m;}public BigDecimal getPrice30m(){return price30m;}public BigDecimal getPrice60m(){return price60m;}public BigDecimal getClosePrice(){return closePrice;}public BigDecimal getHighestPrice(){return highestPrice;}public BigDecimal getLowestPrice(){return lowestPrice;}public BigDecimal getReturn5m(){return return5m;}public BigDecimal getReturn10m(){return return10m;}public BigDecimal getReturn30m(){return return30m;}public BigDecimal getReturn60m(){return return60m;}public BigDecimal getReturnClose(){return returnClose;}public BigDecimal getMaxReturn(){return maxReturn;}public BigDecimal getMaxDrawdown(){return maxDrawdown;}public PerformanceStatus getStatus(){return status;}public String getCalculationVersion(){return calculationVersion;}public Instant getFinalizedAt(){return finalizedAt;}
}
