package com.sunmo.stockplatform.analytics.application;
import com.sunmo.stockplatform.analytics.domain.*;import com.sunmo.stockplatform.analytics.infrastructure.DetectionPerformanceRepository;import com.sunmo.stockplatform.market.application.*;import com.sunmo.stockplatform.market.domain.MarketTick;import com.sunmo.stockplatform.scanner.domain.ScannerDetection;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.Instant;import java.util.Map;
@Service
public class DetectionPerformanceTracker {
 private final DetectionPerformanceRepository repository;private final QuoteStateStore quotes;private final MarketEventGateway events;public DetectionPerformanceTracker(DetectionPerformanceRepository repository,QuoteStateStore quotes,MarketEventGateway events){this.repository=repository;this.quotes=quotes;this.events=events;}
 @Transactional public void initialize(ScannerDetection detection){repository.save(new DetectionPerformance(detection));}
 @Transactional public void onTick(MarketTick tick){for(DetectionPerformance performance:repository.findByDetectionStockStockCodeAndStatus(tick.stockCode(),PerformanceStatus.PENDING)){performance.observe(tick.price(),tick.occurredAt());events.publish("scanner.performance.updated",Map.of("detectionId",performance.getDetection().getId(),"stockCode",tick.stockCode(),"status",performance.getStatus().name()));}}
 @Scheduled(cron="0 31 15 * * MON-FRI",zone="Asia/Seoul") @Transactional public void finalizeMarketClose(){Instant now=Instant.now();for(DetectionPerformance performance:repository.findByStatus(PerformanceStatus.PENDING)){var tick=quotes.get(performance.getDetection().getStock().getStockCode()).orElse(null);performance.finalizeClose(tick==null?null:tick.price(),now);events.publish("scanner.performance.updated",Map.of("detectionId",performance.getDetection().getId(),"stockCode",performance.getDetection().getStock().getStockCode(),"status",performance.getStatus().name()));}}
}
