import {useEffect,useState} from 'react'
import {useQuery,useQueryClient} from '@tanstack/react-query'
import {Phase4App} from './Phase4App'
import './phase6.css'
type Detection={id:number;eventId:string;scannerType:'VOLUME'|'PRICE_RISE'|'MOMENTUM';stockCode:string;stockName:string;market:string;detectedAt:string;detectedPrice:number;fiveMinuteChangeRate:number;volumeRatio:number;currentFiveMinuteVolume:number;currentFiveMinuteTradingValue:number;dailyTradingValue:number;momentumScore:number;settingName:string}
type Setting={id:number;name:string;type:string;minChangeRate:number;minVolumeRatio:number;minFiveMinuteTradingValue:number;minDailyTradingValue:number;cooldownSeconds:number;active:boolean}
async function get<T>(url:string):Promise<T>{const r=await fetch(url);if(!r.ok)throw new Error('Scanner 데이터를 불러오지 못했습니다.');return r.json()}
const tabs=[['MOMENTUM','Momentum'],['VOLUME','거래량 급증'],['PRICE_RISE','5분 급등']] as const
function ScannerPage({back}:{back:()=>void}){const [tab,setTab]=useState<Detection['scannerType']>('MOMENTUM'),cache=useQueryClient();const detections=useQuery({queryKey:['detections',tab],queryFn:()=>get<Detection[]>(`/api/v1/scanner-detections?type=${tab}&limit=50`),refetchInterval:10000});const settings=useQuery({queryKey:['scanner-settings'],queryFn:()=>get<Setting[]>('/api/v1/scanner-settings')});useEffect(()=>{if(typeof EventSource==='undefined')return;const source=new EventSource('/api/v1/stream');const refresh=()=>cache.invalidateQueries({queryKey:['detections']});['scanner.volume.detected','scanner.price.detected','scanner.momentum.detected'].forEach(name=>source.addEventListener(name,refresh));return()=>source.close()},[cache]);return <div className="scannerPage"><header><button onClick={back}>← 대시보드</button><div><p>PHASE 6 · MARKET SCANNER</p><h1>실시간 Scanner</h1><span>5분봉의 가격과 거래량 변화를 조건별로 탐지합니다.</span></div><aside><small>현재 설정</small><b>{settings.data?.filter(s=>s.active).length??0}</b><span>활성 Preset</span></aside></header><main><nav>{tabs.map(([key,label])=><button className={tab===key?'active':''} onClick={()=>setTab(key)} key={key}>{label}</button>)}</nav><section className="scannerGrid"><div className="detectionList"><div className="listTitle"><span><small>LIVE DETECTIONS</small><h2>{tabs.find(t=>t[0]===tab)?.[1]}</h2></span><b>{detections.data?.length??0}</b></div>{detections.isLoading&&<div className="scannerEmpty">불러오는 중…</div>}{detections.error&&<div className="scannerEmpty">{detections.error.message}</div>}{detections.data?.length===0&&<div className="scannerEmpty"><b>아직 포착된 종목이 없습니다</b><p>정규장 체결과 6개 이상의 5분봉 이력이 필요합니다.</p></div>}{detections.data?.map(item=><article key={item.eventId}><div><i>{item.stockName[0]}</i><span><b>{item.stockName}</b><small>{item.stockCode} · {item.market} · {new Date(item.detectedAt).toLocaleTimeString('ko-KR')}</small></span><strong>{item.detectedPrice.toLocaleString()}원</strong></div><dl><span><dt>5분 등락</dt><dd className={item.fiveMinuteChangeRate>=0?'hot':'cold'}>{item.fiveMinuteChangeRate?.toFixed(2)}%</dd></span><span><dt>거래량 비율</dt><dd>{item.volumeRatio?.toFixed(2)}×</dd></span><span><dt>5분 거래대금</dt><dd>{Math.round(item.currentFiveMinuteTradingValue/1000000).toLocaleString()}백만</dd></span><span><dt>Score</dt><dd>{item.momentumScore?.toFixed(2)}</dd></span></dl></article>)}</div><aside className="settingPanel"><h2>Scanner 설정</h2>{settings.data?.map(s=><div className={!s.active?'disabled':''} key={s.id}><span><b>{s.name}</b><small>{s.type}</small></span><p>등락 ≥ {s.minChangeRate}%</p><p>거래량 ≥ {s.minVolumeRatio}×</p><p>Cooldown {s.cooldownSeconds}초</p></div>)}</aside></section></main></div>}
export function Phase6App(){const[scanner,setScanner]=useState(false);return scanner?<ScannerPage back={()=>setScanner(false)}/>:<><button className="scannerLaunch" onClick={()=>setScanner(true)}>⚡ Scanner</button><Phase4App/></>}
